= Register Description File

Register Explorer uses a register description file to provide a hierarchical view into the design under test (DUT).

The register description files use YAML syntax, and must have either a `.yml` or .yaml file extension.
If you're new to YAML and want to learn more, see "https://learnxinyminutes.com/docs/yaml/Learn[YAML in Y minutes]."

Register description files are intended to be generated via a register automation solution.

== Root Object

The root object is a map of elements indexed by element ID.

[source,yaml]
.Partial register description example
----
reg0:
  type: reg
  name: reg0
  offset: 0x0
  fields:
    - name: f1
      lsb: 16
      nbits: 16
      access: rw
    - name: f0
      lsb: 0
      nbits: 16
      access: rw

reg1:
  type: reg
  name: reg1
  offset: 0x4
  fields:
    - name: f0
      lsb: 0
      nbits: 32
      access: ro
----

== Metadata

Because the register description will likely change from version to version of the DUT, an optional metadata key is provided on the root object.
The metadata key provides a method of communicating version information for matching a version of the register description to a version of the DUT.

[source,yaml]
.Metadata example
----
metadata:
  dut:
    name: Example DUT
    version: v0.1
----

== Elements

Elements are specified in a flat structure and describe a tree structure via element to element references.
A flat structure is used to simplify and optimize lookups.

There are four element types.

* Root (`root`)
* Block (`blk`)
* Register (`reg`)
* Memory (`mem`)

The element type is specified via the element `type` key.

=== The Root Element (`root`)

The register description must contain a single `root` element.
The `root` element is the entry point into the design.
It is idenfied as the root node via the `root` element ID and via the `type: root` key-value pair.

The `root` element contains one or more children.
Children are specified as a sequence of element IDs under the element `chilren` key.

[source,yaml]
.Root element example
----
root:
  type: root
  children:
    - child0
    - child1
----

=== Block Elements (`blk`)

Block elements are a grouping other elements.
They are identified as blocks via the `type: blk` key-value pair.
Block elements can contain `reg`, `mem`, and other `blk` elements.
They have the following keys:

* `type`: `blk`
* `offset`: The offset (bytes) of the memory relative to its parent.
* `size`: The size (bytes) of the memory.
* `children`: A sequence of element IDs.

[source,yaml]
.Block element example
----
block0:
  type: blk
  offset: 0x0
  size: 0x1000
  children:
    - block1
    - reg0
    - mem0
----

=== Register Elements (`reg`)

Register elements describe 32-bit hardware registers.
They are identified as registers via the `type: reg` key-value pair.
They have the following keys:

* `type`: `reg`
* `id`: A copy of the element ID
* `offset`: The offset (bytes) of the register relative to its parent.
* `doc`: The documentation for the register.
* `fields`: A sequence of field objects.

==== Field Objects

Field objects describe an n-bit register field.
They have the following keys:

* `name`: The name of the field.
* `nbits`: The size of the field in bits.
* `lsb`: The index of the least significant bit of the field relative to the register.
* `access`: The software access type of the field.
* `doc`: The documentation for the field.

==== Register Element Example

[source,yaml]
.Register element example
----
reg0:
  type: reg
  name: reg0
  offset: 0x0
  doc: An example register.
  fields:
    - name: f1
      lsb: 16
      nbits: 16
      access: rw
      doc: An example field.
    - name: f0
      lsb: 0
      nbits: 16
      access: rw
      doc: Another example field.
----

=== Memory Elements (`mem`)

Memory elements describe contiguous blocks of memory.
They are identified as memories via the `type: mem` key-value pair.
They have the following keys:

* `type`: `mem`
* `offset`: The offset (bytes) of the memory relative to its parent.
* `size`: The size (bytes) of the memory.
* `doc`: The documentation for the memory.

== Register Description File Example

[source,yaml]
.`register_description.yml`
----
metadata:
  dut:
    name: Example DUT
    version: v0.1

root:
  type: root
  children:
    - regs
    - mems

regs:
  type: blk
  offset: 0x0
  size: 0x1_0000
  children:
    - regs.blk0
    - regs.blk1

mems:
  type: blk
  offset: 0x1_0000
  size: 0x1_0000
  children:
    - mems.mem0
    - mems.mem1

regs.blk0:
  type: blk
  offset: 0x0
  size: 0x1000
  children:
    - regs.blk0.reg0
    - regs.blk0.reg1

regs.blk1:
  type: blk
  offset: 0x1000
  size: 0x1000
  children:
    - regs.blk1.reg0
    - regs.blk1.reg1

regs.blk0.reg0:
  type: reg
  name: regs.blk0.reg0
  offset: 0x0
  fields:
    - name: field
      lsb: 0
      nbits: 32
      access: rw

regs.blk0.reg1:
  type: reg
  name: regs.blk0.reg1
  offset: 0x0
  fields:
    - name: field
      lsb: 0
      nbits: 32
      access: rw

regs.blk1.reg0:
  type: reg
  name: regs.blk1.reg0
  offset: 0x0
  fields:
    - name: field
      lsb: 0
      nbits: 32
      access: rw

regs.blk1.reg1:
  type: reg
  name: regs.blk1.reg1
  offset: 0x0
  fields:
    - name: field
      lsb: 0
      nbits: 32
      access: rw

mems.mem0:
  type: mem
  offset: 0x0
  size: 0x8000

mems.mem1:
  type: mem
  offset: 0x8000
  size: 0x8000
----
